apiVersion: v1
kind: Namespace
metadata:
  name: temporal
  labels:
    name: temporal
    purpose: temporal-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: workers
  labels:
    name: workers
    purpose: temporal-workers
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
    purpose: infrastructure